spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: nw-cloud-config-dev
---
spring:
  profiles: test
  application:
    name: nw-cloud-config-test

#  请保存为UTF-8格式